### ISSUE TITLE
radvd 2.18 on macOS: no route to host

### ISSUE THREAD

**Issue by tvand** [radvd-project/radvd#122]
I compiled radvd 2.18 from source on macOS High Sierra. The host to run this has two network interfaces, en0 and en3. I'd like to announce a route on en3.

The log file shows:
```
[Jun 02 10:50:54] radvd (42324): sending RA to ff02::1 on en3 (fe80::ca8:9178:40a1:c51), 3 options (using 72/1210 bytes)
[Jun 02 10:50:54] radvd (42324): sendmsg: No route to host
[Jun 02 10:50:54] radvd (42324): send_ra_forall failed on interface en3
```

If I try to `ping6 ff02::1`, I get the same behavior - no route to host. Pinging `ff02::1%en3` works, however. Could it be that the zone index is missing or wrong? How would I debug this?

**Comment by stappersg** [comment]
FWIW   v2.19 has been released.

**Comment by reubenhwk** [comment]
If you haven't already, try increasing the log level...

" -d, --debug=NUM Set the debug level. Values can be 1, 2, 3, 4 or 5.\n"

...and see what else the log tells you.  I used to compile radvd and test
it on OSX, but haven't been doing so for a long while.  It uses some
different sources vs linux.  The OSX stuff is most likely using the bsd44
source rather than the linux ones (some of the files are conditionally
compiled based on the platform).  If you can debug radvd on OSX and get it
working, I'd be happy to merge the changes.

Thanks in advance,
Reuben

**Comment by stappersg** [comment]
I would like to have the privilege of power to close issues like this.
Yes, I saying that I, teammember of _radvd project_, feel unable to help.

**Comment by stappersg** [comment]
(Thanks for granting, now using that privilege to reduce the number of open issues.)

@tvand it is the lack of any follow-up from you that made me close this issue. Do know that the
>  If you can debug radvd on OSX and get it working, I'd be happy to merge the changes.

is since closing of #135

>  If you can debug radvd on OSX and get it working, we are happy to merge the changes.
