### ISSUE TITLE
Improvements/build issues for FreeBSD

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [radvd-project/radvd#145]
Hi,

We may integrate some FreeBSD upstream patches into next radvd release, like this one : https://github.com/freebsd/freebsd-ports/blob/master/net/radvd/files/patch-device-bsd44.c (I did not try yet to build master radvd with this patch applied, I currently have some autoconf issues with FreeBSD 12).
There is also this patch : https://github.com/freebsd/freebsd-ports/blob/master/net/radvd/files/patch-interface.c.

What do you think about these integrations ?

I will keep this issue updated, I will need help for autotool.

**Comment by RICCIARDI-Adrien** [comment]
OK, it will be up to FreeBSD guys to show up if they want to upstream their patches.

Are the "check" tests, built and executed with command `make check`, intended to work on BSD ?

**Comment by robbat2** [comment]
I emailed the author of those patches

**Comment by fichtner** [comment]
So I did respond in October 2021 a little late but perhaps we want to pick this back up now?

**Comment by stappersg** [comment]
> So I did respond in October 2021 

Where?


> perhaps we want to pick this back up now?

There is meanwhile #217

**Comment by fichtner** [comment]
Can we not play this game after another 2 years of silence? I got an email, I responded and followed up here. The patch reasons are known and documented and the scope in FreeBSD has also shifted over time.

The main question is what is the radvd plan here?

**Comment by fichtner** [comment]
And #217 simply lacks context. 😉

**Comment by robbat2** [comment]
Hi @fichtner 

I checked my email archives and I don't see any response from you in 2021.

Can you please submit cleaned versions of those patches as PRs, with commit message descriptions/signed-off-by DCO statements (It's unclear who wrote the patches).
https://github.com/freebsd/freebsd-ports/blob/master/net/radvd/files/patch-device-bsd44.c 
https://github.com/freebsd/freebsd-ports/blob/master/net/radvd/files/patch-interface.c

I also see that the first patch does NOT populate the `cleanup_allrouters_membership`  function.
What is FreeBSDs behavior in this case? On Linux, the cleanup is needed so that the host leaves the all-routers multicast group.

**Comment by fichtner** [comment]
Hi @robbat2,

This was the message:

```
From: Franco Fichtner <franco@opnsense.org>
Subject: Re: FreeBSD patches to radvd
Date: Thu, 28 Oct 2021 11:04:39 +0200
To: "Robin H. Johnson" <robbat2@gentoo.org>

Hi Robin,

Sorry for the late response.

> On 2. Apr 2021, at 7:38 AM, Robin H. Johnson <robbat2@gentoo.org> wrote:
> 
> I've recently taken over a leadership role maintaining radvd.

Nice to hear.  Thank you for your work!

> Could you have a look at this issue regarding FreeBSD support in radvd:
> https://github.com/radvd-project/radvd/issues/145
> 
> and then consider submitted the FreeBSD patches to radvd to us as
> upstream?

It looks like the FreeBSD ports tree is a good fit for two reasons:

(1) Implementation might differ between BSDs slightly.

(2) There is a bug in FreeBSD 12 upwards that depletes the amount of
multicast joins but it is almost impossible to trigger.  The patches
mitigate this issue by trying to hold on to the multicast membership
instead of doing the previous leave/join dance that worked fine on
FreeBSD 11.  Unfortunately nobody found the reason and FreeBSD committers
are unaware of this issue although it has real world impact on OPNsense
and pfSense -- long story short radvd is only really used there in the
FreeBSD scope.

> I've read them, but I don't understand why FreeBSD needs those patches.
> That information should probably be captured in comments and/or commit
> messages.

Maybe that's clearer now.  I would also point to this issue where we
tracked the work...

https://github.com/opnsense/core/issues/4338

If you have more questions let me know.


Cheers,
Franco
```

The bug we spoke of was found and fixed in FreeBSD this year. https://github.com/opnsense/src/commit/93e9cefd053

There was also an attempt predating this but it only fixed the lesser half of the issue. https://github.com/opnsense/src/commit/3eebc6234b0

`setup_allrouters_membership()` appears to be portable now. cleanup_allrouters_membership() is more or less automatic on process stop. I'm not sure how dynamic radvd can be operated, but with prefix deprecation needing a restart or adding new interfaces it's essentially always doing what it should.

patch-interface.c changes were only required to address https://github.com/opnsense/src/commit/93e9cefd053 and superseded by https://github.com/opnsense/src/commit/3eebc6234b0 so I think I can submit a patch to remove this one from FreeBSD.

I hope this clears up the questions.


Cheers,
Franco

**Comment by fichtner** [comment]
Hmm, give me a bit of time to see if `check_ip6_iface_forwarding()` is still as it should be and clean up the other things in the port. I can also fill `cleanup_allrouters_membership()` for completeness. Testing this is easy enough.

> Do we need to conditionally check for the fix to support older BSD releases?

As far as FreeBSD 13.2 and 14.0 are concerned they work ok with the EADDRINUSE safeguard. Older FreeBSD releases are no longer supported anyway.

> To be clear, I can just move those two functions into device-common.c and all of the BSDs will work?

Well, knowing they can handle additional patching via their ports trees I don't think it's a huge issue going forward with this and if so they might upstream a small ifdef for their operating system, e.g. in the `check_ip6_iface_forwarding()` case.

Naturally I don't want to speak for any of the BSDs with OPNsense being a side show, but I think the goal of integrating "BSD" is worth doing and the feedback will trickle in if the integration needs tweaking for a particular BSD.


Cheers,
Franco

**Comment by heliosfa** [comment]
I've done some testing on this with FreeBSD 14 and the only patch needed to make things work is the changes to `setup_allrouters_membership()` in device-bsd44.c

```
diff --git a/device-bsd44.c b/device-bsd44.c
index e788c20..e85f88c 100644
--- a/device-bsd44.c
+++ b/device-bsd44.c
@@ -127,15 +127,25 @@ ret:

 int setup_allrouters_membership(int sock, struct Interface *iface)
 {
-       return 0;
-
-       /* Quoting:
-       https://github.com/radvd-project/radvd/issues/145#issuecomment-810466476
+       struct ipv6_mreq mreq;
+
+       memset(&mreq, 0, sizeof(mreq));
+       mreq.ipv6mr_interface = iface->props.if_index;
+
+       /* all-routers multicast address */
+       if (inet_pton(AF_INET6, "ff02::2",
+                       &mreq.ipv6mr_multiaddr.s6_addr) != 1) {
+               flog(LOG_ERR, "inet_pton failed");
+               return (-1);
+       }

-       OK, it will be up to FreeBSD guys to show up
-       if they want to upstream their patches.
+       if (setsockopt(sock, IPPROTO_IPV6, IPV6_JOIN_GROUP,
+                       &mreq, sizeof(mreq)) < 0 && errno != EADDRINUSE) {
+               flog(LOG_ERR, "can't join ipv6-allrouters on %s", iface->props.name);
+               return (-1);
+       }

-       */
+       return 0;
 }
```

Without this, radvd doesn't respond to router solicitations from clients.

**Comment by fichtner** [comment]
@heliosfa if the patch corresponds to https://github.com/freebsd/freebsd-ports/blob/main/net/radvd/files/patch-device-bsd44.c then that is fine. I will point out that `check_ip6_iface_forwarding` is patched in FreeBSD dating back to:

https://github.com/freebsd/freebsd-ports/commit/773d8b58
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245393

> While here, squelch the "IPv6 forwarding on interface seems to be disabled, but continuing anyway" message because it has no programmatic consequence and the flag is not supported on BSD anyway.

I suspect that 2.20 will have issues in FreeBSD due to the volume of changes going in, but they can only be addressed when it arrives eventually.


Cheers,
Franco

**Comment by Neustradamus** [comment]
@pandrewhk, @miwi-fbsd, @dhn, @bapt, @rbgarga, @olgeni, @farrokhi, @droso, @mat813, @tcberner, @stesser, @nunotexbsd: What do you think?

Thanks in advance.

**Comment by heliosfa** [comment]
> @heliosfa if the patch corresponds to https://github.com/freebsd/freebsd-ports/blob/main/net/radvd/files/patch-device-bsd44.c then that is fine.

That's the one. I've been running radvd-2.20-rc1 on pfsense since Feb with no issues.

**Comment by fichtner** [comment]
Ok nice, shall I offer a PR then?

**Comment by Neustradamus** [comment]
@fichtner: Yes, it is for this I have added tags of people of FreeBSD: @dhn, @farrokhi, @mat813 and more:
- https://github.com/freebsd/freebsd-ports/commits/main/net/radvd
- https://github.com/freebsd/freebsd-ports/commits/main/net/radvd/files/patch-device-bsd44.c

**Comment by fichtner** [comment]
No need to call the cavalry -- let me do it this afternoon. :)


Cheers,
Franco

**Comment by Neustradamus** [comment]
@fichtner: In your PR, please add:
Submitted by:	Geoffrey Sisson <geoff@dns-oarc.net>
- https://github.com/freebsd/freebsd-ports/commit/eec4114162c06cb5b592ecc0a3487ebd2189a1a0

**Comment by fichtner** [comment]
Done #241

**Comment by stappersg** [comment]
> Done #241

And now closing this issue.
Main reason is the wish for moving forward, the idea of not be hold back by this old issue.

In case I was too hasty to close, please make a fresh start (new merge request or new issue) to get the radvd project forward.

**Comment by fichtner** [comment]
Thanks, will do a bit more QA with the current development state on OPNsense/FreeBSD on Monday just to be sure.


Cheers,
Franco
