### ISSUE TITLE
Truncated sentance in radvd.conf manpage?

### ISSUE THREAD

**Issue by mbooth101** [radvd-project/radvd#230]
See: 

https://github.com/radvd-project/radvd/blob/f2de4764559e102fe8492520be328858af0f964d/radvd.conf.5.man#L117-L128

The paragraph ends with:

> ... but may be useful in combination with VRRP or other functionality that 

Or other functionality that ***does what,*** radvd? I didn't expect this cliff-hanger and I'm being held in suspense :-D

**Comment by reubenhwk** [comment]
On Mar 6, 2024, at 3:50 AM, Mat Booth ***@***.***> wrote:﻿
See:
https://github.com/radvd-project/radvd/blob/f2de4764559e102fe8492520be328858af0f964d/radvd.conf.5.man#L117-L128
The paragraph ends with:

... but may be useful in combination with VRRP or other functionality that

Or other functionality that does what, radvd? I didn't expect this cliff-hanger and I'm being held in suspense :-D

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
Guess nobody ever read that far into the man page. 🤣

**Comment by reubenhwk** [comment]
Robin, look like you were the author of this comment back in 2016.  Can you complete it?

commit 9aad6f02decbb65946121aef9347c17f659124b0
Author: Robin H. Johnson <robbat2@gentoo.org>
Date:   Fri Nov 11 16:19:13 2016 -0800

    AdvRASrcAddress: selection of RA source address
