### ISSUE TITLE
radvd sends out RAs to wrong interface

### ISSUE THREAD

**Issue by petrus-lt** [radvd-project/radvd#25]
I'm using radvd on an openvpn tap interface. When the vpn server is restarted, the tap interface goes down and up, and radvd starts advertising on the lan interface:

```
root@host:~# radvdump
#
# radvd configuration generated by radvdump 1.8.5
# based on Router Advertisement from fe80::81:37
# received by interface eth0
#
interface eth0
{
        AdvSendAdvert on;
        # Note: {Min,Max}RtrAdvInterval cannot be obtained with radvdump
        AdvManagedFlag off;
        AdvOtherConfigFlag off;
        AdvReachableTime 0;
        AdvRetransTimer 0;
        AdvCurHopLimit 64;
        AdvDefaultLifetime 1800;
        AdvHomeAgentFlag off;
        AdvDefaultPreference high;
        AdvSourceLLAddress on;

        prefix 2001:db8:8081:3701::/64
        {
                AdvValidLifetime 86400;
                AdvPreferredLifetime 14400;
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr off;
        }; # End of prefix definition

}; # End of interface definition
```

tcpdump -i eth0 confirms this: 

```
08:30:11.987462 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 56) fe80::81:37 > ip6-allnodes: [icmp6 sum ok] ICMP6, router advertisement, length 56
        hop limit 64, Flags [none], pref high, router lifetime 1800s, reachable time 0s, retrans time 0s
          prefix info option (3), length 32 (4): 2001:db8:8081:3700::/64, Flags [onlink, auto], valid time 86400s, pref. time 14400s
          source link-address option (1), length 8 (1): fa:c7:02:73:4a:1e
```

The radvd config contains only the openvpn interface: 

```
# cat /etc/radvd.conf
interface tap-vpn
{
   AdvSendAdvert on;
   AdvDefaultPreference high;
   prefix 2001:db8:8081:3701::/64
   {
   };
};
```

The monitoring confirms that the issue appeared at the exact moment when the vpn server was restarted. 

My openvpn config has the 'persist-tun' option, so the tap interface is in fact not destroyed but goes down.

**Comment by andihofmeister** [comment]
I had the same problem.

Turns out that I tried to change the firewall mark on the packets via ip6tables. Apparently this causes the packets to be re-routed whereby the scope_id and in6_pktinfo get lost. After removing my marking rules, the problem was gone.

Environment was kernel 4.4.36, iptables 1.4.21 and radvd 2.15

Hope that helps
Andi

**Comment by rozmansi** [comment]
I have been banging my head against the wall for the last few days trying to solve this problem too.

Thanks to @andihofmeister, I have found that an `ip6tables -t mangle -A OUTPUT -p ipv6-icmp -j MARK --set-mark 0x1` causes all RAs to different subnets to be rerouted thru the same interface.

Kernel: 4.13.0, radvd: 2.16

**Comment by Neustradamus** [comment]
Any news?

**Comment by mm1ke** [comment]
For some days now I'm also trying to fix this issue on my firewall.

I have two physical interfaces: `enp2s0` and `enp1s0`. On `enp1s0` there are also 2 vlans configured: `enp1s0.70` and `enp1s0.80`.
For the interfaces `enp1s0` and the two vlans I'm having a radvd config which provides these interfaces with IPv6. There are ULA's and GUA's addresses configured. The config looks as following:

```
interface enp1s0 {
        AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        prefix fda1:1111:222:60::/64 {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
        prefix 2a0a:4444:555:60::/64 {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
};

interface enp1s0.70 {
        AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        prefix fda1:1111:222:70::/64 {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
        prefix 2a0a:4444:555:70::/64 {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
};

interface enp1s0.80 {
        AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        prefix fda1:1111:222:80::/64 {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
        prefix 2a0a:4444:555:80::/64 {
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr on;
        };
};
```
Software: `radvd-2.19`
System: `Linux s1 5.10.27-gentoo #2 SMP PREEMPT Fri Apr 30 15:54:12 CEST 2021 x86_64 AMD G-T40E Processor AuthenticAMD GNU/Linux`

For the Clients in the Vlans the configuration _seems_ to work as expected.
However, Clients from the interface `enp2s0` would get addresses from `enp1s0` and vice versa (if i enable ipv6 there too). I've already tried many things like setting `AdvRASrcAddress` but with no success so far. 

I also can reproduce it with android and windows clients very easy. 
However, interestingly with linux-clients it doesn't happen everywhere. While one wireless client also gets wrong ipv6 addresses, two other wired clients doesn't seem to be affected. Maybe this has something todo with the network-clients used by the clients? (The wireless uses `NetworkManager`, while the two wired uses `netifrc` - all are gentoo/openrc based clients)

There is also a firewall configured. However, instead of `iptables` I'm using `nftables`. I've already tried many config adaptations but with no success so far too. Even without any rules the behavior is the same. The networks are also completely separated, so there exists no firewall rules which allows any traffic between them.

@rozmansi @andihofmeister 
Any idea how i can find out if packet marks are being modified/added? I clearly doesn't have any rule in nft configured, but maybe something else modifies these packages..?

Would be great if someone could look into this. Right now i basically can't use ipv6 because of this.

**Comment by Neustradamus** [comment]
@robbat2: What do you think?

**Comment by broetchen** [comment]
similar issue here:
prefix configured for eth0 is announced on eth0.99 - that makes ipv6 on eth0.99 unuseable, no workaround known.

**Comment by robbat2** [comment]
I cannot reproduce this, even with the `ip6tables` command provided. 

Running 
`Linux bohr-int 5.14.5-x86_64 #88 SMP Fri Sep 17 22:30:09 PDT 2021 x86_64 AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux`

@broetchen can you please run the attached `setup.sh` script. It depends on the `teardown.sh` and `trigger.sh` scripts, and will create the dummy0 and tap42 devices for testing.
[setup.sh.txt](https://github.com/radvd-project/radvd/files/7836954/setup.sh.txt)
[trigger.sh.txt](https://github.com/radvd-project/radvd/files/7836955/trigger.sh.txt)
[teardown.sh.txt](https://github.com/radvd-project/radvd/files/7836956/teardown.sh.txt)
Rename them to `.sh` (because GitHub does not permit attachments otherwise), and give them chmod 755, run as root.

**Comment by mm1ke** [comment]
Some more information what i could fine out regarding this issue.

In my case it seems like there were 2 problems at hand, one of which i could fix.

First the wlan clients (android, etc):
Initially i though that it might have something to do with the dhcp-client used by the clients. As mentioned my only laptop who uses `networkmanager` instead of openrc was also affected while the lan clients where not. However `networkmanager` wasn't the problem. 
Since i was also looking into my network devices it turned out that the wlan APs made the problems for the wlan clients. (it was an old tp-link ap). After changing the AP (this time a lancom ap), Android Clients and other wlan clients doesn't get IPv6 addresses from the wrong vlan anymore.
I don't know what the AP did, but it seems his IPv6 stack was somehow buggy, which also leads me also to the windows Clients.

Windows Clients:
While i could fix my wlan clients (which includes windows client here), windows clients which are physical connected to a port that also has other vlans tagged on it, still get ipv6 addresses from these vlans.
However, this might not be a problem to only radvd as i found following information:
https://community.arubanetworks.com/community-home/digestviewer/viewthread?MID=31121

I don't know what HP switches uses for dhcpv6 (maybe it uses radvd too?), but at least you'll get the same problem there too, and it seems only windows clients are affected. Seems like the ipv6 stack from windows is buggy too?

Personally i only have one windows client and since i knew what todo i either remove all tagged vlans from the port where it's connected or simple connect the client via wlan (which is the usual case anyway).

Hope this information helps someone.

Regards
Michael

**Comment by broetchen** [comment]
after removing temporary switched off adv in config (so it does not announce a wrong addresse) radvd now does the correct advs. Cannot reproduce anymore :-/ sorry And to make it clear: no other changes were made. hmm

**Comment by stappersg** [comment]
Thanks for reporting the _Cannot reproduce anymore_.

This issue now waits again for _how to reproduce information_.

**Comment by robbat2** [comment]
@broetchen maybe you can still reproduce it, and capture good data?

My gut feeling is that what users have seen it actually a packet coming back from the switchgear, and that they didn't expect that. Plus `tcpdump` doesn't normally tell you which device & direction the packet was in, making it very easy to get confused.

The testing scripts I posted are very careful to log interfaces & packet directions.

**Comment by mcr** [comment]
tcpdump -i any -e 
will give you In/Out/Multicast tags, which can be useful here.  The Linux Cooked Header is, however, missing other fields.

**Comment by Neustradamus** [comment]
@ all, do you reproduce this bug?
If yes, can you add logs?

**Comment by robbat2** [comment]
No response for 6 months, closing.
